// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlJcP51FEXW8iEGsTboBgCN7fusUM_ug',
    appId: '1:1038375640500:web:5fd20c5eeeb8ecf64126e1',
    messagingSenderId: '1038375640500',
    projectId: 'ecommerce-6aad2',
    authDomain: 'ecommerce-6aad2.firebaseapp.com',
    storageBucket: 'ecommerce-6aad2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQS6hYZUlkm0vG4phKqtn3gkJ8vc4d30c',
    appId: '1:1038375640500:android:55061266bef452ee4126e1',
    messagingSenderId: '1038375640500',
    projectId: 'ecommerce-6aad2',
    storageBucket: 'ecommerce-6aad2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnyhi05FRYyoHlf26FIYLxJ3KIRGFYYk',
    appId: '1:1038375640500:ios:cc39690d55bd21ad4126e1',
    messagingSenderId: '1038375640500',
    projectId: 'ecommerce-6aad2',
    storageBucket: 'ecommerce-6aad2.appspot.com',
    androidClientId: '1038375640500-d6v4b78189nff5sonm458lmf2qf0stck.apps.googleusercontent.com',
    iosClientId: '1038375640500-kechc6i15j2cd8v0474ln0sf1126cpbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
